# Generated by Django 4.2.30 on 2026-08-26 12:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cookbook', '0012_prepkitchen_alter_productionrecipe_prep_kitchen_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Capability',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('label', models.CharField(max_length=150)),
                ('group', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'capabilities',
                'ordering': ['group', 'label'],
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=80, unique=True)),
                ('description', models.TextField(blank=True)),
                ('grants_all_branches', models.BooleanField(default=False)),
                ('grants_all_prep_kitchens', models.BooleanField(default=False)),
                ('is_system', models.BooleanField(default=False)),
                ('capabilities', models.ManyToManyField(blank=True, related_name='roles', to='accounts.capability')),
                ('default_branches', models.ManyToManyField(blank=True, related_name='default_for_roles', to='cookbook.branch')),
                ('default_prep_kitchens', models.ManyToManyField(blank=True, related_name='default_for_roles', to='cookbook.prepkitchen')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('display_name', models.CharField(blank=True, max_length=150)),
                ('scope_overridden', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True, help_text='Deactivate to block sign-in access.')),
                ('branches', models.ManyToManyField(blank=True, related_name='scoped_users', to='cookbook.branch')),
                ('denied_capabilities', models.ManyToManyField(blank=True, related_name='denied_to', to='accounts.capability')),
                ('extra_capabilities', models.ManyToManyField(blank=True, related_name='granted_to', to='accounts.capability')),
                ('prep_kitchens', models.ManyToManyField(blank=True, related_name='scoped_users', to='cookbook.prepkitchen')),
                ('role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='accounts.role')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['user__username'],
            },
        ),
    ]
