# Generated by Django 4.2.30 on 2026-08-25 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cookbook', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dishrecipe',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='productionrecipe',
            options={'ordering': ['-created_at']},
        ),
    ]
