# Generated by Django 4.2.30 on 2026-08-25 12:17

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('cookbook', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemConversion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('item_sku', models.CharField(help_text='SKU of the inventory-platform Item this supplements.', max_length=100, unique=True)),
                ('note_to_add', models.TextField(blank=True)),
                ('grams_per_piece', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('pieces_per_pack', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('pieces_per_kg', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('pieces_or_pack_per_box', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='cookbook.approver')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='cookbook.approver')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ItemNutrition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('item_sku', models.CharField(max_length=100, unique=True)),
                ('calories', models.DecimalField(decimal_places=3, default=0, max_digits=10)),
                ('fat_g', models.DecimalField(decimal_places=3, default=0, max_digits=10)),
                ('protein_g', models.DecimalField(decimal_places=3, default=0, max_digits=10)),
                ('saturated_fat_g', models.DecimalField(decimal_places=3, default=0, max_digits=10)),
                ('trans_fat_g', models.DecimalField(decimal_places=3, default=0, max_digits=10)),
                ('cholesterol_mg', models.DecimalField(decimal_places=3, default=0, max_digits=10)),
                ('sodium_mg', models.DecimalField(decimal_places=3, default=0, max_digits=10)),
                ('carbs_g', models.DecimalField(decimal_places=3, default=0, max_digits=10)),
                ('fibers_g', models.DecimalField(decimal_places=3, default=0, max_digits=10)),
                ('sugars_g', models.DecimalField(decimal_places=3, default=0, max_digits=10)),
                ('added_sugars_g', models.DecimalField(decimal_places=3, default=0, max_digits=10)),
                ('verification_notes', models.CharField(blank=True, help_text='e.g. "OK", "Check Required - All values zero", "OK - Non-Food".', max_length=255)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='cookbook.approver')),
                ('unit_scale', models.ForeignKey(help_text='The unit these values are per, e.g. per gram, per ml, per each.', on_delete=django.db.models.deletion.PROTECT, related_name='+', to='cookbook.unitscale')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='cookbook.approver')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ItemConversionLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('label', models.CharField(help_text='e.g. "1 Tbs", "1/2 Ts", "1/8 Cup".', max_length=20)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=12)),
                ('gram_equivalent', models.DecimalField(blank=True, decimal_places=3, help_text='Secondary gram conversion, only used for ml-based ingredients.', max_digits=12, null=True)),
                ('item_conversion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='cookbook.itemconversion')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='cookbook.unitscale')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
