# Generated by Django 4.2.30 on 2026-08-25 12:58

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('cookbook', '0002_alter_dishrecipe_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductionRecipeActivityLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('action_type', models.CharField(choices=[('created', 'Created'), ('updated', 'Updated'), ('recalculated', 'Cost recalculated'), ('deleted', 'Deleted')], max_length=15)),
                ('description', models.TextField(blank=True)),
                ('changed_by', models.CharField(blank=True, help_text='Cookbook username who made the change.', max_length=255)),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_log', to='cookbook.productionrecipe')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProductionCostHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('cost', models.DecimalField(decimal_places=3, max_digits=12)),
                ('output_qty', models.DecimalField(decimal_places=3, max_digits=12)),
                ('production_recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cost_history', to='cookbook.productionrecipe')),
            ],
            options={
                'verbose_name_plural': 'production cost history',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DishRecipeActivityLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('action_type', models.CharField(choices=[('created', 'Created'), ('updated', 'Updated'), ('recalculated', 'Cost recalculated'), ('deleted', 'Deleted')], max_length=15)),
                ('description', models.TextField(blank=True)),
                ('changed_by', models.CharField(blank=True, help_text='Cookbook username who made the change.', max_length=255)),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_log', to='cookbook.dishrecipe')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DishPriceHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('cost', models.DecimalField(decimal_places=3, max_digits=12)),
                ('selling_price', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
                ('dish_recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_history', to='cookbook.dishrecipe')),
            ],
            options={
                'verbose_name_plural': 'dish price history',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
    ]
