# Generated by Django 4.2.30 on 2026-08-26 06:45

from django.db import migrations, models

# code -> (dimension, factor_to_canonical). Canonical: mass=g, volume=ml,
# count=each, length=cm. Cup = 16 Tbs = 240 ml (matches inventory-platform's
# own cup->ml factor). Pinch ~ 1/16 tsp.
UNIT_DIMENSIONS = {
    'g': ('mass', 1), 'Kg': ('mass', 1000),
    'ml': ('volume', 1), 'Ltr': ('volume', 1000),
    'Tbs': ('volume', 15), 'Ts': ('volume', 5),
    'Cup': ('volume', 240), 'Pinch': ('volume', '0.31'),
    'Pc': ('count', 1), 'Pcs': ('count', 1), 'EA': ('count', 1),
    'Portion': ('count', 1),
    'cm': ('length', 1), 'm': ('length', 100),
}


def set_unit_dimensions(apps, schema_editor):
    UnitScale = apps.get_model('cookbook', 'UnitScale')
    for code, (dim, factor) in UNIT_DIMENSIONS.items():
        UnitScale.objects.filter(code=code).update(dimension=dim, factor_to_canonical=factor)


class Migration(migrations.Migration):

    dependencies = [
        ('cookbook', '0003_productionrecipeactivitylog_productioncosthistory_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='unitscale',
            name='dimension',
            field=models.CharField(choices=[('mass', 'Mass'), ('volume', 'Volume'), ('count', 'Count / piece'), ('length', 'Length'), ('other', 'Other')], default='other', max_length=10),
        ),
        migrations.AddField(
            model_name='unitscale',
            name='factor_to_canonical',
            field=models.DecimalField(decimal_places=6, default=1, help_text="Multiply a quantity in this unit by this to get the dimension's canonical unit (g / ml / each / cm).", max_digits=16),
        ),
        migrations.RunPython(set_unit_dimensions, migrations.RunPython.noop),
    ]
