# Generated by Django 4.2.30 on 2026-08-26 06:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cookbook', '0004_unitscale_dimension_unitscale_factor_to_canonical'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemconversion',
            name='base_unit',
            field=models.ForeignKey(blank=True, help_text='Unit the cost is per — g, ml or EA (the sheet\'s "Unit Scale").', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='cookbook.unitscale'),
        ),
        migrations.AddField(
            model_name='itemconversion',
            name='cost_per_base_unit',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='KWD per one base_unit, e.g. 0.001400 KD/g.', max_digits=16, null=True),
        ),
        migrations.AddField(
            model_name='itemconversion',
            name='cost_source',
            field=models.CharField(choices=[('excel_import', 'Excel import'), ('manual', 'Manual entry'), ('inventory_sync', 'Synced from inventory')], default='manual', max_length=20),
        ),
        migrations.AddField(
            model_name='itemconversion',
            name='cost_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='itemconversion',
            name='order_cost',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='KWD per order_unit.', max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='itemconversion',
            name='order_unit',
            field=models.CharField(blank=True, help_text='Purchasing unit, for provenance — "PCS", "KG", "LTR".', max_length=20),
        ),
        migrations.AddField(
            model_name='itemconversion',
            name='pack_qty',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='base_units in one order_unit (the sheet\'s "Total Unit").', max_digits=14, null=True),
        ),
    ]
