# Generated by Django 4.2.30 on 2026-08-26 06:51

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('cookbook', '0005_itemconversion_base_unit_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name_en', models.CharField(max_length=100, unique=True)),
                ('name_ar', models.CharField(blank=True, max_length=100)),
                ('code', models.CharField(blank=True, max_length=20)),
                ('sort_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'branches',
                'ordering': ['sort_order', 'name_en'],
            },
        ),
        migrations.AlterModelOptions(
            name='menucategory',
            options={'ordering': ['sort_order', 'name'], 'verbose_name_plural': 'menu categories'},
        ),
        migrations.AddField(
            model_name='menucategory',
            name='menu_title_ar',
            field=models.CharField(blank=True, help_text='Arabic heading printed on the menu — the sheet keeps this separate from name_ar (it can differ).', max_length=150),
        ),
        migrations.AddField(
            model_name='menucategory',
            name='name_ar',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='menucategory',
            name='sort_order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='dishrecipe',
            name='branch',
            field=models.CharField(blank=True, help_text='Branch this dish belongs to, e.g. "Dine", "Luma", "Levant". Free text for now; branch_ref is the structured version.', max_length=100),
        ),
        migrations.AlterField(
            model_name='tastedescriptor',
            name='category',
            field=models.CharField(choices=[('appearance', 'Appearance'), ('color', 'Color'), ('aroma', 'Aroma'), ('texture', 'Texture'), ('presentation', 'Presentation'), ('primary_flavor', 'Primary flavor'), ('secondary_flavor', 'Secondary flavor'), ('aftertaste', 'Aftertaste'), ('mouthfeel', 'Mouthfeel'), ('freshness', 'Freshness standard'), ('critical_defect', 'Critical defect (not allowed)')], max_length=20),
        ),
        migrations.AddField(
            model_name='dishrecipe',
            name='branch_ref',
            field=models.ForeignKey(blank=True, help_text='Structured branch. Takes over from the `branch` string in a later phase.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='dishes', to='cookbook.branch'),
        ),
    ]
