# Generated by Django 4.2.30 on 2026-08-26 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cookbook', '0006_branch_alter_menucategory_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemconversion',
            name='cost_per_base_unit',
            field=models.DecimalField(blank=True, decimal_places=10, help_text='KWD per one base_unit, e.g. 0.0014000000 KD/g. High precision because it is often order_cost / pack_qty (a repeating decimal).', max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='itemconversion',
            name='order_cost',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='KWD per order_unit.', max_digits=16, null=True),
        ),
    ]
