# Generated by Django 4.2.30 on 2026-08-26 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cookbook', '0007_alter_itemconversion_cost_per_base_unit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dishrecipe',
            name='cost_breakdown',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='dishrecipe',
            name='rating_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dishrecipe',
            name='rating_status',
            field=models.CharField(blank=True, choices=[('ok', 'OK'), ('attention', 'Attention'), ('fix', 'Fix')], help_text='QA alarm shown next to the rating on the menu view.', max_length=10),
        ),
        migrations.AddField(
            model_name='dishrecipe',
            name='recipe_code',
            field=models.CharField(blank=True, db_index=True, help_text='The source cook book\'s dish code, e.g. "1076.9". Stable across versions; the import matches on it.', max_length=30),
        ),
        migrations.AddField(
            model_name='dishrecipe',
            name='revision',
            field=models.CharField(blank=True, help_text='Revision label from the sheet, e.g. "Rev.01" or "Fix".', max_length=20),
        ),
        migrations.AddField(
            model_name='dishrecipe',
            name='revision_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productionrecipe',
            name='cost_breakdown',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='productionrecipe',
            name='recipe_code',
            field=models.CharField(blank=True, db_index=True, help_text='The source cook book\'s dish code, e.g. "1076.9". Stable across versions; the import matches on it.', max_length=30),
        ),
        migrations.AddField(
            model_name='productionrecipe',
            name='revision',
            field=models.CharField(blank=True, help_text='Revision label from the sheet, e.g. "Rev.01" or "Fix".', max_length=20),
        ),
        migrations.AddField(
            model_name='productionrecipe',
            name='revision_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dishrecipe',
            name='labor_cost',
            field=models.DecimalField(decimal_places=3, default=0, help_text='Labour cost per serving/batch (KWD). Recomputed on save from section salary x prep time.', max_digits=12),
        ),
        migrations.AlterField(
            model_name='productionrecipe',
            name='labor_cost',
            field=models.DecimalField(decimal_places=3, default=0, help_text='Labour cost per serving/batch (KWD). Recomputed on save from section salary x prep time.', max_digits=12),
        ),
    ]
