# Generated by Django 4.2.30 on 2026-08-26 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cookbook', '0008_dishrecipe_cost_breakdown_dishrecipe_rating_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dishrecipe',
            name='nutrition',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='dishstandard',
            name='branch_applicability',
            field=models.CharField(blank=True, help_text='"All Branches", "Selected Branches", or a specific branch.', max_length=40),
        ),
        migrations.AddField(
            model_name='itemconversion',
            name='allergens',
            field=models.ManyToManyField(blank=True, help_text='Allergens this item carries — feeds the dish allergen roll-up. Cookbook-local; report upstream if it should be permanent.', related_name='items', to='cookbook.allergen'),
        ),
        migrations.AddField(
            model_name='productionrecipe',
            name='nutrition',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
