# Generated by Django 4.2.30 on 2026-08-26 08:21

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('cookbook', '0009_dishrecipe_nutrition_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(blank=True, help_text='Defaults to "<Branch> Menu".', max_length=120)),
                ('name_ar', models.CharField(blank=True, max_length=120)),
                ('notes', models.TextField(blank=True)),
                ('last_snapshot_at', models.DateTimeField(blank=True, null=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='menus', to='cookbook.branch')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MenuSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('taken_by', models.CharField(blank=True, max_length=255)),
                ('label', models.CharField(blank=True, max_length=120)),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='cookbook.menu')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='dishrecipe',
            name='image_url',
            field=models.URLField(blank=True, help_text='Plated-dish photo shown on the menu and card.'),
        ),
        migrations.CreateModel(
            name='MenuSnapshotLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('dish_name', models.CharField(max_length=255)),
                ('recipe_code', models.CharField(blank=True, max_length=30)),
                ('category', models.CharField(blank=True, max_length=100)),
                ('cost', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('menu_price', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
                ('food_cost_pct', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('snapshot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='cookbook.menusnapshot')),
            ],
            options={
                'ordering': ['dish_name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MenuLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('menu_price', models.DecimalField(blank=True, decimal_places=3, help_text='Price on this branch menu. Falls back to the recipe selling_price.', max_digits=12, null=True)),
                ('pos_name', models.CharField(blank=True, max_length=255)),
                ('image_url', models.URLField(blank=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_available', models.BooleanField(default=True)),
                ('dish', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='menu_lines', to='cookbook.dishrecipe')),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='cookbook.menu')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
                'abstract': False,
                'unique_together': {('menu', 'dish')},
            },
        ),
        migrations.AddConstraint(
            model_name='menu',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('branch',), name='one_active_menu_per_branch'),
        ),
    ]
