# Generated by Django 4.2.30 on 2026-08-26 10:57

import uuid

from django.db import migrations, models


def backfill_lineage(apps, schema_editor):
    """Group existing versions of one recipe under a shared lineage_key.

    recipe_code is stable across versions and is what the import matches on,
    so rows that share a non-blank code share a lineage. Every row with a
    blank code becomes its own lineage. Assigned explicitly here rather than
    trusting the AddField default (which can apply one value to every row).
    """
    for model_name in ('DishRecipe', 'ProductionRecipe'):
        Model = apps.get_model('cookbook', model_name)

        codes = (Model.objects.exclude(recipe_code='')
                 .values_list('recipe_code', flat=True).distinct())
        for code in codes:
            Model.objects.filter(recipe_code=code).update(lineage_key=uuid.uuid4())

        for pk in Model.objects.filter(recipe_code='').values_list('pk', flat=True):
            Model.objects.filter(pk=pk).update(lineage_key=uuid.uuid4())


class Migration(migrations.Migration):

    dependencies = [
        ('cookbook', '0010_menu_menusnapshot_dishrecipe_image_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dishrecipe',
            name='lineage_key',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
        ),
        migrations.AddField(
            model_name='productionrecipe',
            name='lineage_key',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
        ),
        migrations.RunPython(backfill_lineage, migrations.RunPython.noop),
    ]
