# Generated by Django 4.2.30 on 2026-08-26 12:13

from django.db import migrations, models
import django.db.models.deletion
import uuid

# Starter prep kitchens — admin-editable afterwards.
PREP_KITCHENS = [
    ('Bread', 'المخبز', 'BRD'),
    ('Sauce', 'الصلصات', 'SAU'),
    ('Hot Line', 'الطبخ الساخن', 'HOT'),
    ('Meat', 'اللحوم', 'MEA'),
    ('Poultry', 'الدواجن', 'POU'),
    ('Seafood', 'المأكولات البحرية', 'SEA'),
    ('Cold Prep', 'التحضير البارد', 'CLD'),
    ('Rice & Grains', 'الأرز والحبوب', 'RIC'),
    ('Pastry', 'الحلويات', 'PAS'),
]


def seed_and_backfill(apps, schema_editor):
    PrepKitchen = apps.get_model('cookbook', 'PrepKitchen')
    ProductionRecipe = apps.get_model('cookbook', 'ProductionRecipe')

    by_name = {}
    for i, (en, ar, code) in enumerate(PREP_KITCHENS):
        pk, _ = PrepKitchen.objects.get_or_create(
            name_en=en, defaults={'name_ar': ar, 'code': code, 'sort_order': i})
        by_name[en.lower()] = pk

    # backfill prep_kitchen_ref from the free-text label where it clearly matches
    for recipe in ProductionRecipe.objects.exclude(prep_kitchen='').filter(prep_kitchen_ref__isnull=True):
        label = recipe.prep_kitchen.strip().lower()
        match = by_name.get(label) or next(
            (pk for name, pk in by_name.items() if name in label or label in name), None)
        if match:
            recipe.prep_kitchen_ref = match
            recipe.save(update_fields=['prep_kitchen_ref'])


class Migration(migrations.Migration):

    dependencies = [
        ('cookbook', '0011_dishrecipe_lineage_key_productionrecipe_lineage_key'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrepKitchen',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name_en', models.CharField(max_length=100, unique=True)),
                ('name_ar', models.CharField(blank=True, max_length=100)),
                ('code', models.CharField(blank=True, max_length=20)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('inventory_store_id', models.CharField(blank=True, help_text='inventory-platform production-store id this prep kitchen maps to.', max_length=64)),
            ],
            options={
                'ordering': ['sort_order', 'name_en'],
            },
        ),
        migrations.AlterField(
            model_name='productionrecipe',
            name='prep_kitchen',
            field=models.CharField(blank=True, help_text='Which prep kitchen this recipe belongs to (e.g. "Bread & Sauces"). Free text label; prep_kitchen_ref is the structured version.', max_length=255),
        ),
        migrations.AddField(
            model_name='productionrecipe',
            name='prep_kitchen_ref',
            field=models.ForeignKey(blank=True, help_text='Structured prep kitchen. Prep-cook access is scoped to this.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='production_recipes', to='cookbook.prepkitchen'),
        ),
        migrations.RunPython(seed_and_backfill, migrations.RunPython.noop),
    ]
