# Generated by Django 4.2.30 on 2026-08-28 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cookbook', '0012_prepkitchen_alter_productionrecipe_prep_kitchen_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dishrecipeactivitylog',
            name='action_type',
            field=models.CharField(choices=[('created', 'Created'), ('updated', 'Updated'), ('recalculated', 'Cost recalculated'), ('deleted', 'Deleted'), ('standard_updated', 'QA standard updated'), ('standard_approved', 'QA standard approved')], max_length=20),
        ),
        migrations.AlterField(
            model_name='productionrecipeactivitylog',
            name='action_type',
            field=models.CharField(choices=[('created', 'Created'), ('updated', 'Updated'), ('recalculated', 'Cost recalculated'), ('deleted', 'Deleted'), ('standard_updated', 'QA standard updated'), ('standard_approved', 'QA standard approved')], max_length=20),
        ),
    ]
