# Generated by Django 4.2.30 on 2026-08-28 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cookbook', '0013_alter_dishrecipeactivitylog_action_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dishrecipe',
            name='inventory_recipe_id',
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
        migrations.AddField(
            model_name='dishrecipe',
            name='publish_error',
            field=models.TextField(blank=True, help_text='Last publish failure; cleared on the next success.'),
        ),
        migrations.AddField(
            model_name='dishrecipe',
            name='published_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productionrecipe',
            name='inventory_recipe_id',
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
        migrations.AddField(
            model_name='productionrecipe',
            name='publish_error',
            field=models.TextField(blank=True, help_text='Last publish failure; cleared on the next success.'),
        ),
        migrations.AddField(
            model_name='productionrecipe',
            name='published_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
