# Generated by Django 4.2.30 on 2026-08-29 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cookbook', '0015_alter_dishrecipeactivitylog_action_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dishrecipe',
            name='image',
            field=models.ImageField(blank=True, help_text='Uploaded plated-dish photo. Takes precedence over image_url.', null=True, upload_to='dish-images/'),
        ),
        migrations.AlterField(
            model_name='dishrecipe',
            name='image_url',
            field=models.URLField(blank=True, help_text="External plated-dish photo URL. Set automatically to the uploaded file's URL when `image` is present; may also hold a manual link.", max_length=500),
        ),
    ]
