# Generated by Django 4.2.30 on 2026-08-31 11:39

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('cookbook', '0016_dishrecipe_image_alter_dishrecipe_image_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatingGuide',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('plate_spec', models.CharField(blank=True, help_text='Plate / vessel and prep, e.g. "28 cm white coupe, warmed".', max_length=255)),
                ('garnish_spec_en', models.TextField(blank=True)),
                ('garnish_spec_ar', models.TextField(blank=True)),
                ('build_notes_en', models.TextField(blank=True, help_text='Component order and placement on the plate.')),
                ('build_notes_ar', models.TextField(blank=True)),
                ('common_errors_en', models.TextField(blank=True, help_text='What QA sees go wrong most often.')),
                ('common_errors_ar', models.TextField(blank=True)),
                ('pickup_window_seconds', models.PositiveIntegerField(blank=True, help_text='Seconds from plate-up to hand-off before quality drops.', null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='cookbook.approver')),
                ('dish_recipe', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='plating', to='cookbook.dishrecipe')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='cookbook.approver')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='dishrecipeactivitylog',
            name='action_type',
            field=models.CharField(choices=[('created', 'Created'), ('updated', 'Updated'), ('recalculated', 'Cost recalculated'), ('deleted', 'Deleted'), ('standard_updated', 'QA standard updated'), ('standard_approved', 'QA standard approved'), ('plating_updated', 'Plating guide updated'), ('published', 'Published to inventory')], max_length=20),
        ),
        migrations.AlterField(
            model_name='productionrecipeactivitylog',
            name='action_type',
            field=models.CharField(choices=[('created', 'Created'), ('updated', 'Updated'), ('recalculated', 'Cost recalculated'), ('deleted', 'Deleted'), ('standard_updated', 'QA standard updated'), ('standard_approved', 'QA standard approved'), ('plating_updated', 'Plating guide updated'), ('published', 'Published to inventory')], max_length=20),
        ),
        migrations.CreateModel(
            name='PlatingImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('image', models.ImageField(upload_to='plating/')),
                ('caption_en', models.CharField(blank=True, max_length=255)),
                ('caption_ar', models.CharField(blank=True, max_length=255)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('pins', models.JSONField(blank=True, default=list)),
                ('guide', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='cookbook.platingguide')),
            ],
            options={
                'ordering': ['sort_order', 'created_at'],
                'abstract': False,
            },
        ),
    ]
