# Generated by Django 4.2.30 on 2026-08-31 12:17

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('cookbook', '0017_platingguide_alter_dishrecipeactivitylog_action_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemStorage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('item_sku', models.CharField(max_length=100, unique=True)),
                ('storage_band', models.CharField(blank=True, choices=[('dry', 'Dry store'), ('chilled', 'Chilled'), ('frozen', 'Frozen')], max_length=10)),
                ('shelf_life_hours', models.PositiveIntegerField(blank=True, help_text='Hours from prep / production to use-by — drives the date label.', null=True)),
                ('opened_shelf_life_hours', models.PositiveIntegerField(blank=True, help_text='Shorter life once opened / thawed / decanted.', null=True)),
                ('storage_instructions_en', models.TextField(blank=True)),
                ('storage_instructions_ar', models.TextField(blank=True)),
                ('label_notes_en', models.CharField(blank=True, help_text='Extra line printed on the date label.', max_length=255)),
                ('label_notes_ar', models.CharField(blank=True, max_length=255)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='cookbook.approver')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='cookbook.approver')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
    ]
