# Generated by Django 4.2.30 on 2026-09-02 05:58

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('cookbook', '0019_digestsubscription'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuPeriod',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('kind', models.CharField(choices=[('seasonal', 'Seasonal'), ('daily_special', 'Daily special'), ('event', 'Event')], max_length=15)),
                ('name_en', models.CharField(max_length=120)),
                ('name_ar', models.CharField(blank=True, max_length=120)),
                ('starts_on', models.DateField()),
                ('ends_on', models.DateField(blank=True, help_text='Blank = open-ended.', null=True)),
                ('weekday_mask', models.PositiveSmallIntegerField(default=127, help_text='Which weekdays the period is active. Bit 0 = Monday … bit 6 = Sunday; 127 = every day. Lets a "Friday special" recur.')),
                ('is_live', models.BooleanField(default=True, help_text='Uncheck to hold the period as a draft the resolver ignores.')),
                ('notes', models.TextField(blank=True)),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='periods', to='cookbook.menu')),
            ],
            options={
                'ordering': ['-starts_on', 'name_en'],
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='menuline',
            name='menu_description_ar',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='menuline',
            name='menu_description_en',
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name='MenuPeriodLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('op', models.CharField(choices=[('add', 'Add dish'), ('remove', 'Remove dish'), ('reprice', 'Change price'), ('replace_photo', 'Swap photo'), ('replace_copy', 'Rewrite description')], max_length=15)),
                ('menu_price', models.DecimalField(blank=True, decimal_places=3, help_text='For add / reprice.', max_digits=12, null=True)),
                ('image_url', models.URLField(blank=True, help_text='For add / replace_photo.')),
                ('description_en', models.TextField(blank=True, help_text='For add / replace_copy.')),
                ('description_ar', models.TextField(blank=True)),
                ('pos_name', models.CharField(blank=True, help_text='For add.', max_length=255)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('dish', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='cookbook.dishrecipe')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='cookbook.menuperiod')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
                'abstract': False,
                'unique_together': {('period', 'dish', 'op')},
            },
        ),
    ]
