# Generated by Django 4.2.30 on 2026-09-02 06:33

from django.db import migrations, models
from django.utils.text import slugify
import django.db.models.deletion
import uuid


def backfill_slugs(apps, schema_editor):
    Branch = apps.get_model('cookbook', 'Branch')
    seen = set()
    for branch in Branch.objects.all().order_by('sort_order', 'name_en'):
        base = slugify(branch.name_en) or 'branch'
        candidate, n = base, 2
        while candidate in seen:
            candidate, n = f'{base}-{n}', n + 1
        seen.add(candidate)
        branch.slug = candidate
        branch.save(update_fields=['slug'])


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('cookbook', '0020_menuperiod_menuline_menu_description_ar_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='slug',
            field=models.SlugField(blank=True, default='', max_length=60),
            preserve_default=False,
        ),
        migrations.RunPython(backfill_slugs, noop),
        migrations.AlterField(
            model_name='branch',
            name='slug',
            field=models.SlugField(blank=True, max_length=60, unique=True),
        ),
        migrations.CreateModel(
            name='MenuEdition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('lineage_key', models.UUIDField(db_index=True, default=uuid.uuid4, help_text='Groups every edition of one menu (survives a menu rebuild).')),
                ('version', models.PositiveIntegerField(default=1)),
                ('is_current', models.BooleanField(default=True)),
                ('effective_on', models.DateField(help_text='The date the effective menu was resolved for.')),
                ('published_by', models.CharField(blank=True, max_length=255)),
                ('payload', models.JSONField(default=dict, help_text='Frozen public menu. Never contains cost, margin or supplier data.')),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='editions', to='cookbook.menu')),
            ],
            options={
                'ordering': ['-version'],
                'abstract': False,
            },
        ),
        migrations.AddConstraint(
            model_name='menuedition',
            constraint=models.UniqueConstraint(condition=models.Q(('is_current', True)), fields=('menu',), name='one_current_edition_per_menu'),
        ),
    ]
