# Generated by Django 4.2.30 on 2026-09-02 08:41

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('cookbook', '0021_branch_slug_menuedition_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModifierGroup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name_en', models.CharField(max_length=120, unique=True)),
                ('name_ar', models.CharField(blank=True, max_length=120)),
                ('selection', models.CharField(choices=[('single', 'Pick one'), ('multi', 'Pick several')], default='single', max_length=10)),
                ('min_select', models.PositiveSmallIntegerField(default=0, help_text='Minimum options a customer must choose. 1 = a required pick.')),
                ('max_select', models.PositiveSmallIntegerField(blank=True, help_text='Maximum options. Null = no limit. N for a "pick N" set.', null=True)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['name_en'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ModifierOption',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name_en', models.CharField(max_length=160)),
                ('name_ar', models.CharField(blank=True, max_length=160)),
                ('price_delta', models.DecimalField(decimal_places=3, default=0, help_text='Added to the menu-line price when this option is chosen (KWD).', max_digits=12)),
                ('kind', models.CharField(choices=[('choice', 'Free choice'), ('type', 'Variant (own recipe)'), ('addon', 'Add-on ingredient'), ('instruction', 'Instruction / removal')], default='choice', max_length=15)),
                ('pos_mods_string', models.CharField(blank=True, help_text="Exact text from the Lavu 'Sales by Item' report's Mods column — the key inventory-platform matches on.", max_length=255)),
                ('item_sku', models.CharField(blank=True, max_length=100)),
                ('quantity', models.DecimalField(blank=True, decimal_places=3, help_text='Add-on ingredient quantity per portion.', max_digits=12, null=True)),
                ('is_available', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='cookbook.modifiergroup')),
                ('unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='cookbook.unitscale')),
                ('variant_recipe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='cookbook.dishrecipe')),
            ],
            options={
                'ordering': ['sort_order', 'name_en'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MenuLineModifier',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('role', models.CharField(choices=[('forced', 'Forced (required)'), ('optional', 'Optional (add-on)')], default='optional', max_length=10)),
                ('is_shown', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_uses', to='cookbook.modifiergroup')),
                ('menu_line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modifiers', to='cookbook.menuline')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DishModifierGroup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('default_role', models.CharField(choices=[('forced', 'Forced (required)'), ('optional', 'Optional (add-on)')], default='optional', max_length=10)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('dish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modifier_groups', to='cookbook.dishrecipe')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dish_uses', to='cookbook.modifiergroup')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
                'abstract': False,
            },
        ),
        migrations.AddConstraint(
            model_name='modifieroption',
            constraint=models.UniqueConstraint(fields=('group', 'name_en'), name='unique_option_name_per_group'),
        ),
        migrations.AddConstraint(
            model_name='menulinemodifier',
            constraint=models.UniqueConstraint(fields=('menu_line', 'group'), name='unique_group_per_menu_line'),
        ),
        migrations.AddConstraint(
            model_name='dishmodifiergroup',
            constraint=models.UniqueConstraint(fields=('dish', 'group'), name='unique_group_per_dish'),
        ),
    ]
