# Generated by Django 4.2.30 on 2026-09-03 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cookbook', '0022_modifiergroup_modifieroption_menulinemodifier_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productionrecipeingredient',
            name='alt_item_name_snapshot',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='productionrecipeingredient',
            name='alt_item_sku',
            field=models.CharField(blank=True, help_text='Fallback SKU used if item_sku is out of stock when a batch is confirmed.', max_length=100),
        ),
    ]
