# Generated by Django 4.2.30 on 2026-09-03 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cookbook', '0023_productionrecipeingredient_alt_item_name_snapshot_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dishrecipeingredient',
            name='alt_item_name_snapshot',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='dishrecipeingredient',
            name='alt_item_sku',
            field=models.CharField(blank=True, help_text='Fallback SKU used if item_sku is out of stock when a POS sale is deducted.', max_length=100),
        ),
    ]
