# Generated by Django 4.2.30 on 2026-09-07 06:52

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('cookbook', '0024_dishrecipeingredient_alt_item_name_snapshot_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='modifieroption',
            name='no_consumption_impact',
            field=models.BooleanField(default=False, help_text='This option does not change what the kitchen consumes.'),
        ),
        migrations.AlterField(
            model_name='modifieroption',
            name='quantity',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='DEPRECATED — see `deltas`.', max_digits=12, null=True),
        ),
        migrations.CreateModel(
            name='ModifierOptionIngredient',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('item_sku', models.CharField(help_text='SKU of the inventory-platform Item this delta consumes / credits.', max_length=100)),
                ('item_name_snapshot', models.CharField(blank=True, max_length=255)),
                ('quantity', models.DecimalField(decimal_places=3, help_text='Amount per one portion sold (always positive; `direction` sets the sign).', max_digits=12)),
                ('direction', models.CharField(choices=[('add', 'Adds an ingredient'), ('remove', 'Removes an ingredient')], default='add', max_length=6)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deltas', to='cookbook.modifieroption')),
                ('unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='cookbook.unitscale')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
                'abstract': False,
            },
        ),
        migrations.AddConstraint(
            model_name='modifieroptioningredient',
            constraint=models.UniqueConstraint(fields=('option', 'item_sku', 'direction'), name='unique_delta_per_option_sku_direction'),
        ),
    ]
