# Generated by Django 4.2.30 on 2026-09-13 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cookbook', '0026_migrate_inline_addon_to_deltas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='branch',
            name='code',
        ),
    ]
