# Generated by Django 4.2.30 on 2026-09-13 10:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cookbook', '0027_remove_branch_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dishrecipe',
            name='branch',
        ),
        migrations.AlterField(
            model_name='dishrecipe',
            name='branch_ref',
            field=models.ForeignKey(blank=True, help_text='Branch this dish belongs to.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='dishes', to='cookbook.branch'),
        ),
    ]
